version: '2.4'

services:
  yuque-mcp-server:
    build: .
    image: yuque-mcp-server:latest
    container_name: yuque-mcp-server
    restart: unless-stopped
    ports:
      - "6666:3000"
    env_file:
      - .env
    environment:
      - PORT=3000
      - YUQUE_API_TOKEN=${YUQUE_API_TOKEN}
      - YUQUE_API_BASE_URL=${YUQUE_API_BASE_URL}
    volumes:
      - ./logs:/usr/src/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3